import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "CasClinique",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <main className="from-white-50 to-accent-100">
            {children}
          </main>
        </body>
      </html>
    </>
  );
}
